# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 06:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('due_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoteSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('votes_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Votes')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='votes_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Votes'),
        ),
        migrations.AddField(
            model_name='paper',
            name='votes_select',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.VoteSelect'),
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together=set([('user', 'votes_name')]),
        ),
    ]
